version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017

  app:
    build: .
    container_name: flask-app
    command: python -u run.py
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/API_TARGET_DATA
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - MONGODB_HOST = mongodb
      - MONGODB_PORT = 27017
    volumes:
      - .:/flaskAPI-docker

networks:
  networks_bridge:
    external:
        name: networks_bridge










