version: '3'

services:
  build:
    context: app
    dockerfile: Dockerfile
  container_name: build
  image: build
  restart: unless-stopped
  environment:
    APP_ENV: "prod"
    APP_DEBUG: "False"
    APP_PORT: 5000
    MONGODB_DATABASE: 'test'
    MONGODB_USERNAME: 'test'
    MONGODB_PASSWORD: 'test'
    MONGODB_HOSTNAME: 'mongodb'
  volumes:
    - ./app:/app
  depends_on:
    - mongodb
  networks:
    - backend