version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: API_Targetdata
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: 'test'
      MONGODB_USERNAME: 'test'
      MONGODB_PASSWORD: 'test'
      MONGODB_HOSTNAME: 'mongodb'
    volumes:
      - ./app:app-flask/app
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'test'
      MONGO_INITDB_ROOT_PASSWORD: 'test'
      MONGO_INITDB_DATABASE: 'test'
    volumes:
      - ./data:/data/db
    networks:
      - backend